metadata:
  title: Create Document from Template
  owner: product_manager
  model: gpt-5-codex
  reasoning_effort: medium
  verbosity: low

activation:
  when: user runs `create-spec` or `create-prd` command
  principle: "Lean specs. 1-pagers beat 20-page PRDs. Context first, always."

reasoning_control: |
  <reasoning_control>
  - reasoning_effort: medium
  - uncertainty_tolerance: low
  - prefer_act_over_ask: false  # Elicit context before generating
  - termination_policy: "Complete document generation and write file"
  - early_exit_ok: false  # Must complete all sections
  </reasoning_control>

workflow:
  - id: select_template
    type: choice
    prompt: "Which template?"
    options:
      - label: "Lean Product Spec"
        value: prd-tmpl.yaml
        description: "1-2 page product spec (recommended)"
      - label: "Developer Task"
        value: task-tmpl.yaml
        description: "Use create-task instead"
    default: prd-tmpl.yaml

  - id: validate_context
    type: checklist
    critical: true
    prompt: "Before creating any doc, verify context:"
    items:
      - label: "Product vision clear"
        required: true
      - label: "User problem validated (evidence exists)"
        required: true
      - label: "Success criteria defined"
        required: true
    if_missing: gather_context_first

  - id: gather_context_first
    type: conditional
    run: pm-context-checklist.yaml
    next: process_template_sections

  - id: process_template_sections
    type: iterative
    mode: section_by_section
    rule: |
      Process each section sequentially. NEVER generate full doc at once.

      For each section:
      1. Draft content based on template instruction
      2. Present draft with rationale
      3. STOP and ask: "Thoughts on this section?"
      4. Wait for user feedback
      5. Refine based on feedback
      6. Only proceed when user approves

    sections_from: "{{selected_template}}"

    draft_rules:
      - "Keep it concise (follow template max_length)"
      - "Use context7 MCP for tech stack validation"
      - "Challenge assumptions - ask if uncertain"
      - "Cut ruthlessly - what can we NOT include?"

  - id: finalize_document
    type: assembly
    condition: all_sections_approved
    actions:
      - assemble_sections
      - apply_formatting
      - determine_output_path

  - id: write_file
    type: write_to_filesystem
    critical: true
    rules:
      - "NEVER write to agent file (.codex/agents/product_manager.xml)"
      - "NEVER write to template files (.codex/templates/*.yaml)"
      - "ALWAYS create NEW markdown file in appropriate directory"

    output_paths:
      prd-tmpl.yaml: "docs/specs/{{project_name}}-spec.md"
      task-tmpl.yaml: "docs/tasks/{{task_name}}.md"
      default: "docs/{{filename}}.md"

    tool: Write
    confirm: true

  - id: output_summary
    type: message
    template: |
      ✔ Document created: {{full_output_path}}

      Next steps:
      - Review for clarity
      - Share with stakeholders
      - Challenge scope one more time

      File location: {{full_output_path}}

completion:
  checklist:
    - template_selected
    - context_validated
    - all_sections_approved
    - document_written_to_filesystem
    - output_path_confirmed

anti_patterns:
  never:
    - "Generate entire document in one step"
    - "Proceed without user approval on current section"
    - "Skip the 'present and explain' step"
    - "Write 20-page docs when 1 page works"
    - "Write to agent or template files"
    - "Skip context7 validation for tech references"
  always:
    - "Work section by section"
    - "Provide rationale for content"
    - "Engage in collaborative refinement"
    - "Use context7 MCP for tech validation"
    - "Ask: Could this be simpler?"
    - "Create NEW markdown file in docs/"

notes:
  - Section-by-section workflow prevents rework
  - Always use context7 MCP for tech stack references
  - Challenge scope at every step
  - Keep read time under 5 minutes
